# Generated by Django 5.1.1 on 2024-09-04 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeySkills',
            new_name='KeySkill',
        ),
    ]
