# Generated by Django 5.1.1 on 2024-09-04 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_rename_keyskills_keyskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='work_experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.workexperience'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='work_experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.workexperience'),
        ),
    ]
